---
title: "Overview of using apps"
---
## What are apps?

Apps are ready-made "functions" that you can apply to your data without needing to know all the technical details. They are easy to use, even if you're not an expert programmer. Multiple apps can be naturally composed into "pipelines", which are fully equipped for robust and reproducible application to data. In fact, apps and app pipelines can be applied to a single, or thousands, of data file(s) without writing loops or conditionals.

The composable app infrastructure is provided by the `scinexus` package. See the [`scinexus`](https://scinexus.readthedocs.io) documentation for details on composability rules, type checking, batch processing, parallel execution, and progress tracking.

## How do I start to use `cogent3` apps? {#app_start}

Three top-level functions are very useful:

- `available_apps()` identifies what apps are installed (see [Displaying installed apps](available-apps.qmd))
- `app_help()` shows what a given app can do (see [Getting help on an app](app-help.qmd))
- `get_app()` returns an app instance for you to use (see [Getting an app](app-get.qmd))

Two other crucial concepts concern:

- [data store](https://scinexus.readthedocs.io/en/latest/howto/use-data-stores.html)
- [track failures](https://scinexus.readthedocs.io/en/latest/howto/handle-failures.html)

## Types of apps

There are 3 [app types](https://scinexus.readthedocs.io/en/latest/explanation/app-lifecycle.html):

#. loaders (by convention, names starts with `load_<data type>`)
#. writers (by convention, names starts with `write_<data type>`)
#. generic (no naming convention)

As their names imply, loaders load, writers write and generic apps do other operations on data.

## An example

```{python}
#| echo: false

from tempfile import TemporaryDirectory

tmpdir = TemporaryDirectory(dir=".")
path_to_dir = tmpdir.name
```

I illustrate the general approach for a simple example -- extracting third codon positions. As I'm defining a writer, I also need to define the destination (a directory in this case) where it will write to.

```{python}
from cogent3 import get_app, open_data_store

out_dstore = open_data_store(path_to_dir, suffix="fa", mode="w")

loader = get_app("load_aligned", format_name="fasta", moltype="dna")
cpos3 = get_app("take_codon_positions", 3)
writer = get_app("write_seqs", out_dstore, format_name="fasta")
```

There are two ways in which I can apply the three above apps to data:

### 1. Using apps sequentially like functions

```{python}
data = loader("data/primate_brca1.fasta")
just3rd = cpos3(data)
m = writer(just3rd)
```

The resulting alignment `just3rd` will be written into the `out_dstore` directory in fasta format with the same filename as the original data (`"primate_brca1.fasta"`).

::: {.callout-note}
`m` is a [DataMember](https://scinexus.readthedocs.io/en/latest/reference/data-stores.html) of `out_dstore`.
:::

### 2. Composing several apps into a multi-step "process"

We can make this simpler by creating a single composed function.

```{python}
process = loader + cpos3 + writer
m = process("data/primate_brca1.fasta")
```

### Applying a process to multiple data records

To apply a composed function to multiple files requires a [data store](https://scinexus.readthedocs.io/en/latest/howto/use-data-stores.html). Using `open_data_store()` we identify all data files in a directory that we want to analyse, in the following case, all fasta file in the data directory. `process` can be then applied to all records in the data store without having to loop.

```{python}
dstore = open_data_store("data", suffix="fasta", mode="r")
result = process.apply_to(dstore)
```

::: {.callout-note}
`result` is `out_dstore`.
:::

```{python}
#| echo: false
import shutil

shutil.rmtree(path_to_dir, ignore_errors=True)
```
