"""Unit tests for the phylip parser"""

import pytest

import cogent3
from cogent3.parse.phylip import MinimalPhylipParser, get_align_for_phylip
from cogent3.parse.record import RecordError
from cogent3.parse.sequence import PhylipParser

RELAXED_INTERLEAVED = """2 30
Acromyrmex_echinatior_Genome         gtcgtatttg gaatttgggg
Apis_mellifera_Genome                -gcgagttcg aaatttgggg

          cttcttcttc
          cttcttcttc
"""


def test_relaxed_interleaved():
    seqs = dict(MinimalPhylipParser(RELAXED_INTERLEAVED.splitlines()))
    assert list(seqs) == ["Acromyrmex_echinatior_Genome", "Apis_mellifera_Genome"]
    assert seqs["Acromyrmex_echinatior_Genome"] == "GTCGTATTTGGAATTTGGGGCTTCTTCTTC"
    assert seqs["Apis_mellifera_Genome"] == "-GCGAGTTCGAAATTTGGGGCTTCTTCTTC"
    assert {len(s) for s in seqs.values()} == {30}


RELAXED_SEQUENTIAL = """2 30
Acromyrmex_echinatior_Genome  gtcgtatttg
          gaatttgggg
          cttcttcttc
Apis_mellifera_Genome  -gcgagttcg
          aaatttgggg
          cttcttcttc
"""


def test_relaxed_sequential():
    seqs = dict(MinimalPhylipParser(RELAXED_SEQUENTIAL.splitlines()))
    assert list(seqs) == ["Acromyrmex_echinatior_Genome", "Apis_mellifera_Genome"]
    assert seqs["Acromyrmex_echinatior_Genome"] == "GTCGTATTTGGAATTTGGGGCTTCTTCTTC"
    assert seqs["Apis_mellifera_Genome"] == "-GCGAGTTCGAAATTTGGGGCTTCTTCTTC"
    assert {len(s) for s in seqs.values()} == {30}


@pytest.mark.parametrize("data", [RELAXED_INTERLEAVED, RELAXED_SEQUENTIAL])
def test_layout_autodetected(data):
    expected = {
        "Acromyrmex_echinatior_Genome": "GTCGTATTTGGAATTTGGGGCTTCTTCTTC",
        "Apis_mellifera_Genome": "-GCGAGTTCGAAATTTGGGGCTTCTTCTTC",
    }
    assert dict(MinimalPhylipParser(data.splitlines())) == expected


BIG_INTERLEAVED = """10 705 I
Cow       ATGGCATATCCCATACAACTAGGATTCCAAGATGCAACATCACCAATCATAGAAGAACTA
Carp      ATGGCACACCCAACGCAACTAGGTTTCAAGGACGCGGCCATACCCGTTATAGAGGAACTT
Chicken   ATGGCCAACCACTCCCAACTAGGCTTTCAAGACGCCTCATCCCCCATCATAGAAGAGCTC
Human     ATGGCACATGCAGCGCAAGTAGGTCTACAAGACGCTACTTCCCCTATCATAGAAGAGCTT
Loach     ATGGCACATCCCACACAATTAGGATTCCAAGACGCGGCCTCACCCGTAATAGAAGAACTT
Mouse     ATGGCCTACCCATTCCAACTTGGTCTACAAGACGCCACATCCCCTATTATAGAAGAGCTA
Rat       ATGGCTTACCCATTTCAACTTGGCTTACAAGACGCTACATCACCTATCATAGAAGAACTT
Seal      ATGGCATACCCCCTACAAATAGGCCTACAAGATGCAACCTCTCCCATTATAGAGGAGTTA
Whale     ATGGCATATCCATTCCAACTAGGTTTCCAAGATGCAGCATCACCCATCATAGAAGAGCTC
Frog      ATGGCACACCCATCACAATTAGGTTTTCAAGACGCAGCCTCTCCAATTATAGAAGAATTA

CTTCACTTTCATGACCACACGCTAATAATTGTCTTCTTAATTAGCTCATTAGTACTTTAC
CTTCACTTCCACGACCACGCATTAATAATTGTGCTCCTAATTAGCACTTTAGTTTTATAT
GTTGAATTCCACGACCACGCCCTGATAGTCGCACTAGCAATTTGCAGCTTAGTACTCTAC
ATCACCTTTCATGATCACGCCCTCATAATCATTTTCCTTATCTGCTTCCTAGTCCTGTAT
CTTCACTTCCATGACCATGCCCTAATAATTGTATTTTTGATTAGCGCCCTAGTACTTTAT
ATAAATTTCCATGATCACACACTAATAATTGTTTTCCTAATTAGCTCCTTAGTCCTCTAT
ACAAACTTTCATGACCACACCCTAATAATTGTATTCCTCATCAGCTCCCTAGTACTTTAT
CTACACTTCCATGACCACACATTAATAATTGTGTTCCTAATTAGCTCATTAGTACTCTAC
CTACACTTTCACGATCATACACTAATAATCGTTTTTCTAATTAGCTCTTTAGTTCTCTAC
CTTCACTTCCACGACCATACCCTCATAGCCGTTTTTCTTATTAGTACGCTAGTTCTTTAC

ATTATTTCACTAATACTAACGACAAAGCTGACCCATACAAGCACGATAGATGCACAAGAA
ATTATTACTGCAATGGTATCAACTAAACTTACTAATAAATATATTCTAGACTCCCAAGAA
CTTCTAACTCTTATACTTATAGAAAAACTATCA---TCAAACACCGTAGATGCCCAAGAA
GCCCTTTTCCTAACACTCACAACAAAACTAACTAATACTAACATCTCAGACGCTCAGGAA
GTTATTATTACAACCGTCTCAACAAAACTCACTAACATATATATTTTGGACTCACAAGAA
ATCATCTCGCTAATATTAACAACAAAACTAACACATACAAGCACAATAGATGCACAAGAA
ATTATTTCACTAATACTAACAACAAAACTAACACACACAAGCACAATAGACGCCCAAGAA
ATTATCTCACTTATACTAACCACGAAACTCACCCACACAAGTACAATAGACGCACAAGAA
ATTATTACCCTAATGCTTACAACCAAATTAACACATACTAGTACAATAGACGCCCAAGAA
ATTATTACTATTATAATAACTACTAAACTAACTAATACAAACCTAATGGACGCACAAGAG

GTAGAGACAATCTGAACCATTCTGCCCGCCATCATCTTAATTCTAATTGCTCTTCCTTCT
ATCGAAATCGTATGAACCATTCTACCAGCCGTCATTTTAGTACTAATCGCCCTGCCCTCC
GTTGAACTAATCTGAACCATCCTACCCGCTATTGTCCTAGTCCTGCTTGCCCTCCCCTCC
ATAGAAACCGTCTGAACTATCCTGCCCGCCATCATCCTAGTCCTCATCGCCCTCCCATCC
ATTGAAATCGTATGAACTGTGCTCCCTGCCCTAATCCTCATTTTAATCGCCCTCCCCTCA
GTTGAAACCATTTGAACTATTCTACCAGCTGTAATCCTTATCATAATTGCTCTCCCCTCT
GTAGAAACAATTTGAACAATTCTCCCAGCTGTCATTCTTATTCTAATTGCCCTTCCCTCC
GTGGAAACGGTGTGAACGATCCTACCCGCTATCATTTTAATTCTCATTGCCCTACCATCA
GTAGAAACTGTCTGAACTATCCTCCCAGCCATTATCTTAATTTTAATTGCCTTGCCTTCA
ATCGAAATAGTGTGAACTATTATACCAGCTATTAGCCTCATCATAATTGCCCTTCCATCC

TTACGAATTCTATACATAATAGATGAAATCAATAACCCATCTCTTACAGTAAAAACCATA
CTACGCATCCTGTACCTTATAGACGAAATTAACGACCCTCACCTGACAATTAAAGCAATA
CTCCAAATCCTCTACATAATAGACGAAATCGACGAACCTGATCTCACCCTAAAAGCCATC
CTACGCATCCTTTACATAACAGACGAGGTCAACGATCCCTCCCTTACCATCAAATCAATT
CTACGAATTCTATATCTTATAGACGAGATTAATGACCCCCACCTAACAATTAAGGCCATG
CTACGCATTCTATATATAATAGACGAAATCAACAACCCCGTATTAACCGTTAAAACCATA
CTACGAATTCTATACATAATAGACGAGATTAATAACCCAGTTCTAACAGTAAAAACTATA
TTACGAATCCTCTACATAATGGACGAGATCAATAACCCTTCCTTGACCGTAAAAACTATA
TTACGGATCCTTTACATAATAGACGAAGTCAATAACCCCTCCCTCACTGTAAAAACAATA
CTTCGTATCCTATATTTAATAGATGAAGTTAATGATCCACACTTAACAATTAAAGCAATC

GGACATCAGTGATACTGAAGCTATGAGTATACAGATTATGAGGACTTAAGCTTCGACTCC
GGACACCAATGATACTGAAGTTACGAGTATACAGACTATGAAAATCTAGGATTCGACTCC
GGACACCAATGATACTGAACCTATGAATACACAGACTTCAAGGACCTCTCATTTGACTCC
GGCCACCAATGGTACTGAACCTACGAGTACACCGACTACGGCGGACTAATCTTCAACTCC
GGGCACCAATGATACTGAAGCTACGAGTATACTGATTATGAAAACTTAAGTTTTGACTCC
GGGCACCAATGATACTGAAGCTACGAATATACTGACTATGAAGACCTATGCTTTGATTCA
GGACACCAATGATACTGAAGCTATGAATATACTGACTATGAAGACCTATGCTTTGACTCC
GGACATCAGTGATACTGAAGCTATGAGTACACAGACTACGAAGACCTGAACTTTGACTCA
GGTCACCAATGATATTGAAGCTATGAGTATACCGACTACGAAGACCTAAGCTTCGACTCC
GGCCACCAATGATACTGAAGCTACGAATATACTAACTATGAGGATCTCTCATTTGACTCT

TACATAATTCCAACATCAGAATTAAAGCCAGGGGAGCTACGACTATTAGAAGTCGATAAT
TATATAGTACCAACCCAAGACCTTGCCCCCGGACAATTCCGACTTCTGGAAACAGACCAC
TACATAACCCCAACAACAGACCTCCCCCTAGGCCACTTCCGCCTACTAGAAGTCGACCAT
TACATACTTCCCCCATTATTCCTAGAACCAGGCGACCTGCGACTCCTTGACGTTGACAAT
TACATAATCCCCACCCAGGACCTAACCCCTGGACAATTCCGGCTACTAGAGACAGACCAC
TATATAATCCCAACAAACGACCTAAAACCTGGTGAACTACGACTGCTAGAAGTTGATAAC
TACATAATCCCAACCAATGACCTAAAACCAGGTGAACTTCGTCTATTAGAAGTTGATAAT
TATATGATCCCCACACAAGAACTAAAGCCCGGAGAACTACGACTGCTAGAAGTAGACAAT
TATATAATCCCAACATCAGACCTAAAGCCAGGAGAACTACGATTATTAGAAGTAGATAAC
TATATAATTCCAACTAATGACCTTACCCCTGGACAATTCCGGCTGCTAGAAGTTGATAAT

CGAGTTGTACTACCAATAGAAATAACAATCCGAATGTTAGTCTCCTCTGAAGACGTATTA
CGAATAGTTGTTCCAATAGAATCCCCAGTCCGTGTCCTAGTATCTGCTGAAGACGTGCTA
CGCATTGTAATCCCCATAGAATCCCCCATTCGAGTAATCATCACCGCTGATGACGTCCTC
CGAGTAGTACTCCCGATTGAAGCCCCCATTCGTATAATAATTACATCACAAGACGTCTTG
CGAATGGTTGTTCCCATAGAATCCCCTATTCGCATTCTTGTTTCCGCCGAAGATGTACTA
CGAGTCGTTCTGCCAATAGAACTTCCAATCCGTATATTAATTTCATCTGAAGACGTCCTC
CGGGTAGTCTTACCAATAGAACTTCCAATTCGTATACTAATCTCATCCGAAGACGTCCTG
CGAGTAGTCCTCCCAATAGAAATAACAATCCGCATACTAATCTCATCAGAAGATGTACTC
CGAGTTGTCTTACCTATAGAAATAACAATCCGAATATTAGTCTCATCAGAAGACGTACTC
CGAATAGTAGTCCCAATAGAATCTCCAACCCGACTTTTAGTTACAGCCGAAGACGTCCTC

CACTCATGAGCTGTGCCCTCTCTAGGACTAAAAACAGACGCAATCCCAGGCCGTCTAAAC
CATTCTTGAGCTGTTCCATCCCTTGGCGTAAAAATGGACGCAGTCCCAGGACGACTAAAT
CACTCATGAGCCGTACCCGCCCTCGGGGTAAAAACAGACGCAATCCCTGGACGACTAAAT
CACTCATGAGCTGTCCCCACATTAGGCTTAAAAACAGATGCAATTCCCGGACGTCTAAAC
CACTCCTGGGCCCTTCCAGCCATGGGGGTAAAGATAGACGCGGTCCCAGGACGCCTTAAC
CACTCATGAGCAGTCCCCTCCCTAGGACTTAAAACTGATGCCATCCCAGGCCGACTAAAT
CACTCATGAGCCATCCCTTCACTAGGGTTAAAAACCGACGCAATCCCCGGCCGCCTAAAC
CACTCATGAGCCGTACCGTCCCTAGGACTAAAAACTGATGCTATCCCAGGACGACTAAAC
CACTCATGGGCCGTACCCTCCTTGGGCCTAAAAACAGATGCAATCCCAGGACGCCTAAAC
CACTCGTGAGCTGTACCCTCCTTGGGTGTCAAAACAGATGCAATCCCAGGACGACTTCAT

CAAACAACCCTTATATCGTCCCGTCCAGGCTTATATTACGGTCAATGCTCAGAAATTTGC
CAAGCCGCCTTTATTGCCTCACGCCCAGGGGTCTTTTACGGACAATGCTCTGAAATTTGT
CAAACCTCCTTCATCACCACTCGACCAGGAGTGTTTTACGGACAATGCTCAGAAATCTGC
CAAACCACTTTCACCGCTACACGACCGGGGGTATACTACGGTCAATGCTCTGAAATCTGT
CAAACCGCCTTTATTGCCTCCCGCCCCGGGGTATTCTATGGGCAATGCTCAGAAATCTGT
CAAGCAACAGTAACATCAAACCGACCAGGGTTATTCTATGGCCAATGCTCTGAAATTTGT
CAAGCTACAGTCACATCAAACCGACCAGGTCTATTCTATGGCCAATGCTCTGAAATTTGC
CAAACAACCCTAATAACCATACGACCAGGACTGTACTACGGTCAATGCTCAGAAATCTGT
CAAACAACCTTAATATCAACACGACCAGGCCTATTTTATGGACAATGCTCAGAGATCTGC
CAAACATCATTTATTGCTACTCGTCCGGGAGTATTTTACGGACAATGTTCAGAAATTTGC

GGGTCAAACCACAGTTTCATACCCATTGTCCTTGAGTTAGTCCCACTAAAGTACTTTGAA
GGAGCTAATCACAGCTTTATACCAATTGTAGTTGAAGCAGTACCTCTCGAACACTTCGAA
GGAGCTAACCACAGCTACATACCCATTGTAGTAGAGTCTACCCCCCTAAAACACTTTGAA
GGAGCAAACCACAGTTTCATGCCCATCGTCCTAGAATTAATTCCCCTAAAAATCTTTGAA
GGAGCAAACCACAGCTTTATACCCATCGTAGTAGAAGCGGTCCCACTATCTCACTTCGAA
GGATCTAACCATAGCTTTATGCCCATTGTCCTAGAAATGGTTCCACTAAAATATTTCGAA
GGCTCAAATCACAGCTTCATACCCATTGTACTAGAAATAGTGCCTCTAAAATATTTCGAA
GGTTCAAACCACAGCTTCATACCTATTGTCCTCGAATTGGTCCCACTATCCCACTTCGAG
GGCTCAAACCACAGTTTCATACCAATTGTCCTAGAACTAGTACCCCTAGAAGTCTTTGAA
GGAGCAAACCACAGCTTTATACCAATTGTAGTTGAAGCAGTACCGCTAACCGACTTTGAA

AAATGATCTGCGTCAATATTA---------------------TAA
AACTGATCCTCATTAATACTAGAAGACGCCTCGCTAGGAAGCTAA
GCCTGATCCTCACTA------------------CTGTCATCTTAA
ATA---------------------GGGCCCGTATTTACCCTATAG
AACTGGTCCACCCTTATACTAAAAGACGCCTCACTAGGAAGCTAA
AACTGATCTGCTTCAATAATT---------------------TAA
AACTGATCAGCTTCTATAATT---------------------TAA
AAATGATCTACCTCAATGCTT---------------------TAA
AAATGATCTGTATCAATACTA---------------------TAA
AACTGATCTTCATCAATACTA---GAAGCATCACTA------AGA
"""

SPACE_INTERLEAVED = """ 5 176 I
cox2_leita   MAFILSFWMI FLLDSVIVLL SFVCFVCVWI CALLFSTVLL VSKLNNIYCT
cox2_crifa   MAFILSFWMI FLIDAVIVLL SFVCFVCIWI CSLFFSSFLL VSKINNVYCT
cox2_bsalt   MSFIISFWML FLIDSLIVLL SGAIFVCIWI CSLFFLCILF ICKLDYIFCS
cox2_trybb   MSFILTFWMI FLMDSIIVLI SFSIFLSVWI CALIIATVLT VTKINNIYCT
cox2_tborr   MLFFINQLLL LLVDTFVILE IFSLFVCVFI IVMYILFINY NIFLKNINVY

             WDFTASKFID VYWFTIGGMF SLGLLLRLCL LLYFGHLNFV SFDLCKVVGF
             WDFTASKFID AYWFTIGGMF VLCLLLRLCL LLYFGCLNFV SFDLCKVVGF
             WDFISAKFID LYWFTLGCLF IVCLLIRLCL LLYFSCLNFV CFDLCKCIGF
             WDFISSKFID TYWFVLGMMF ILCLLLRLCL LLYFSCINFV SFDLCKVIGF
             LDFIGSKYLD LYWFLIGIFF VIVLLIRLCL LLYYSWISLL IFDLCKIMGF

             QWYWVYFIFG ETTIFSNLIL ESDYMIGDLR LLQCNHVLTL LSLVIYKLWL
             QWYWVYFIFG ETTIFSNLIL ESDYLIGDLR LLQCNHVLTL LSLVIYKLWL
             QWYWVYFIFG ETTIFSNLIL ESDYLIGDLR LLQCNHVLTL LSLVIYKVWL
             QWYWVYFLFG ETTIFSNLIL ESDYLIGDLR ILQCNHVLTL LSLVIYKLWV
             QWYWIFFVFK ENVIFSNLLI ESDYWIGDLR LLQCNNTFNL ICLVVYKIWV

             SAVDVIHSFA ISSLGVKVEN LVAVMK
             SAVDVIHSFA VSSLGIKVDC IPGRCN
             SAIDVIHSFT LANLGIKVD? ?PGRCN
             SAVDVIHSFT ISSLGIKVEN PGRCNE
             TSIDVIHSFT ISTLGIKIDC IPGRCN
"""

INTERLEAVED_LITTLE = """   6   39 I
Archaeopt CGATGCTTAC CGCCGATGCT
HesperorniCGTTACTCGT TGTCGTTACT
BaluchitheTAATGTTAAT TGTTAATGTT
B. virginiTAATGTTCGT TGTTAATGTT
BrontosaurCAAAACCCAT CATCAAAACC
B.subtilisGGCAGCCAAT CACGGCAGCC

TACCGCCGAT GCTTACCGC
CGTTGTCGTT ACTCGTTGT
AATTGTTAAT GTTAATTGT
CGTTGTTAAT GTTCGTTGT
CATCATCAAA ACCCATCAT
AATCACGGCA GCCAATCAC
"""

NONINTERLEAVED_LITTLE = """   6   20

Archaeopt CGATGCTTAC CGCCGATGCT
HesperorniCGTTACTCGT TGTCGTTACT

BaluchitheTAATGTTAAT TGTTAATGTT
B. virginiTAATGTTCGT TGTTAATGTT
BrontosaurCAAAACCCAT CATCAAAACC
B.subtilisGGCAGCCAAT CACGGCAGCC
"""

NONINTERLEAVED_BIG = """10  297
Rhesus    tgtggcacaaatactcatgccagctcattacagcatgagaac---agtttgttactcact
          aaagacagaatgaatgtagaaaaggctgaattctgtaataaaagcaaacagcctggcttg
          gcaaggagccaacataacagatggactggaagtaaggaaacatgtaatgataggcagact
          cccagcacagagaaaaaggtagatctgaatgctaatgccctgtatgagagaaaagaatgg
          aataagcaaaaactgccatgctctgagaatcctagagacactgaagatgttccttgg
Manatee   tgtggcacaaatactcatgccagctcattacagcatgagaatagcagtttattactcact
          aaagacagaatgaatgtagaaaaggctgaattctgtcataaaagcaaacagcctggctta
          acaaggagccagcagagcagatgggctgaaagtaaggaaacatgtaatgataggcagact
          cctagcacagagaaaaaggtagatatgaatgctaatccattgtatgagagaaaagaagtg
          aataagcagaaacctccatgctccgagagtgttagagatacacaagatattccttgg
Pig       tgtggcacagatactcatgccagctcgttacagcatgagaacagcagtttattactcact
          aaagacagaatgaatgtagaaaaggctgaattttgtaataaaagcaagcagcctgtctta
          gcaaagagccaacagagcagatgggctgaaagtaagggcacatgtaatgataggcagact
          cctaacacagagaaaaaggtagttctgaatactgatctcctgtatgggagaaacgaactg
          aataagcagaaacctgcgtgctctgacagtcctagagattcccaagatgttccttgg
"""


def test_empty():
    assert list(MinimalPhylipParser([])) == []


def test_strict_interleaved_big():
    seqs = list(MinimalPhylipParser(BIG_INTERLEAVED.splitlines(), strict_mode=True))
    assert len(seqs) == 10
    assert seqs[0][0] == "Cow"
    label, seq = seqs[-1]
    assert label == "Frog"
    assert seq == (
        "ATGGCACACCCATCACAATTAGGTTTTCAAGACGCAGCCTCTCCAATTATAGAAGAATTA"
        "CTTCACTTCCACGACCATACCCTCATAGCCGTTTTTCTTATTAGTACGCTAGTTCTTTAC"
        "ATTATTACTATTATAATAACTACTAAACTAACTAATACAAACCTAATGGACGCACAAGAG"
        "ATCGAAATAGTGTGAACTATTATACCAGCTATTAGCCTCATCATAATTGCCCTTCCATCC"
        "CTTCGTATCCTATATTTAATAGATGAAGTTAATGATCCACACTTAACAATTAAAGCAATC"
        "GGCCACCAATGATACTGAAGCTACGAATATACTAACTATGAGGATCTCTCATTTGACTCT"
        "TATATAATTCCAACTAATGACCTTACCCCTGGACAATTCCGGCTGCTAGAAGTTGATAAT"
        "CGAATAGTAGTCCCAATAGAATCTCCAACCCGACTTTTAGTTACAGCCGAAGACGTCCTC"
        "CACTCGTGAGCTGTACCCTCCTTGGGTGTCAAAACAGATGCAATCCCAGGACGACTTCAT"
        "CAAACATCATTTATTGCTACTCGTCCGGGAGTATTTTACGGACAATGTTCAGAAATTTGC"
        "GGAGCAAACCACAGCTTTATACCAATTGTAGTTGAAGCAGTACCGCTAACCGACTTTGAA"
        "AACTGATCTTCATCAATACTA---GAAGCATCACTA------AGA"
    )


def test_strict_space_interleaved():
    seqs = list(MinimalPhylipParser(SPACE_INTERLEAVED.splitlines(), strict_mode=True))
    assert len(seqs) == 5
    assert seqs[0][0] == "cox2_leita"
    assert seqs[-1][0] == "cox2_tborr"
    assert {len(seq) for _, seq in seqs} == {176}


def test_strict_interleaved_little():
    seqs = list(MinimalPhylipParser(INTERLEAVED_LITTLE.splitlines(), strict_mode=True))
    assert len(seqs) == 6
    assert seqs[1][0] == "Hesperorni"
    assert seqs[-1][0] == "B.subtilis"
    assert seqs[-1][1] == "GGCAGCCAATCACGGCAGCCAATCACGGCAGCCAATCAC"


def test_strict_sequential_little():
    seqs = list(
        MinimalPhylipParser(NONINTERLEAVED_LITTLE.splitlines(), strict_mode=True)
    )
    assert len(seqs) == 6
    assert seqs[0][0] == "Archaeopt"
    assert seqs[-1][0] == "B.subtilis"
    assert seqs[-1][1] == "GGCAGCCAATCACGGCAGCC"


def test_strict_sequential_big():
    seqs = list(MinimalPhylipParser(NONINTERLEAVED_BIG.splitlines(), strict_mode=True))
    assert len(seqs) == 3
    assert seqs[0][0] == "Rhesus"
    assert seqs[-1][0] == "Pig"
    assert seqs[-1][1] == (
        "TGTGGCACAGATACTCATGCCAGCTCGTTACAGCATGAGAACAGCAGTTTATTACTCACT"
        "AAAGACAGAATGAATGTAGAAAAGGCTGAATTTTGTAATAAAAGCAAGCAGCCTGTCTTA"
        "GCAAAGAGCCAACAGAGCAGATGGGCTGAAAGTAAGGGCACATGTAATGATAGGCAGACT"
        "CCTAACACAGAGAAAAAGGTAGTTCTGAATACTGATCTCCTGTATGGGAGAAACGAACTG"
        "AATAAGCAGAAACCTGCGTGCTCTGACAGTCCTAGAGATTCCCAAGATGTTCCTTGG"
    )


def test_strict_get_align_interleaved():
    align = get_align_for_phylip(INTERLEAVED_LITTLE.splitlines(), strict_mode=True)
    assert str(align) == (
        ">Archaeopt\nCGATGCTTACCGCCGATGCTTACCGCCGATGCTTACCGC\n"
        ">Hesperorni\nCGTTACTCGTTGTCGTTACTCGTTGTCGTTACTCGTTGT\n"
        ">Baluchithe\nTAATGTTAATTGTTAATGTTAATTGTTAATGTTAATTGT\n"
        ">B. virgini\nTAATGTTCGTTGTTAATGTTCGTTGTTAATGTTCGTTGT\n"
        ">Brontosaur\nCAAAACCCATCATCAAAACCCATCATCAAAACCCATCAT\n"
        ">B.subtilis\nGGCAGCCAATCACGGCAGCCAATCACGGCAGCCAATCAC\n"
    )


def test_strict_get_align_sequential():
    align = get_align_for_phylip(NONINTERLEAVED_LITTLE.splitlines(), strict_mode=True)
    assert str(align) == (
        ">Archaeopt\nCGATGCTTACCGCCGATGCT\n"
        ">Hesperorni\nCGTTACTCGTTGTCGTTACT\n"
        ">Baluchithe\nTAATGTTAATTGTTAATGTT\n"
        ">B. virgini\nTAATGTTCGTTGTTAATGTT\n"
        ">Brontosaur\nCAAAACCCATCATCAAAACC\n"
        ">B.subtilis\nGGCAGCCAATCACGGCAGCC\n"
    )


def test_forced_interleaved_matches_autodetect():
    data = RELAXED_INTERLEAVED.splitlines()
    assert dict(MinimalPhylipParser(data, interleaved=True)) == dict(
        MinimalPhylipParser(data)
    )


def test_forced_sequential_matches_autodetect():
    data = RELAXED_SEQUENTIAL.splitlines()
    assert dict(MinimalPhylipParser(data, interleaved=False)) == dict(
        MinimalPhylipParser(data)
    )


def test_forced_wrong_layout_raises():
    with pytest.raises(RecordError):
        list(MinimalPhylipParser(RELAXED_SEQUENTIAL.splitlines(), interleaved=True))


BAD_LENGTH = """2 40
seq1  ACGTACGTAC
seq2  ACGTACGTAC
"""


def test_length_mismatch_raises():
    with pytest.raises(RecordError):
        list(MinimalPhylipParser(BAD_LENGTH.splitlines()))


def test_header_only_yields_nothing():
    assert list(MinimalPhylipParser(["2 30"])) == []


def test_blank_lines_only_yields_nothing():
    assert list(MinimalPhylipParser(["", "   ", "\t"])) == []


def _lower_converter(data: bytes) -> str:
    return data.decode("utf8").replace(" ", "").replace("\n", "").lower()


def test_custom_converter_applied():
    seqs = dict(
        MinimalPhylipParser(
            RELAXED_INTERLEAVED.splitlines(), converter=_lower_converter
        )
    )
    assert seqs["Apis_mellifera_Genome"] == "-gcgagttcgaaatttggggcttcttcttc"


def test_phylip_parser_accepts_converter():
    assert PhylipParser().accepts_converter is True


def test_load_aligned_seqs_relaxed(tmp_path):
    path = tmp_path / "locus.phy"
    path.write_text(RELAXED_INTERLEAVED)
    aln = cogent3.load_aligned_seqs(path, moltype="dna")
    assert aln.num_seqs == 2
    assert set(aln.names) == {"Acromyrmex_echinatior_Genome", "Apis_mellifera_Genome"}
    assert len(aln) == 30
    seq = str(aln.get_gapped_seq("Apis_mellifera_Genome"))
    assert seq == "-GCGAGTTCGAAATTTGGGGCTTCTTCTTC"


def test_id_map_renames_labels():
    id_map = {"Apis_mellifera_Genome": "bee"}
    seqs = dict(MinimalPhylipParser(RELAXED_INTERLEAVED.splitlines(), id_map=id_map))
    assert "Apis_mellifera_Genome" not in seqs
    assert seqs["bee"] == "-GCGAGTTCGAAATTTGGGGCTTCTTCTTC"


SINGLE_SEQUENCE = """1 20
seq1  ACGTACGTAC
      GTACGTACGT
"""


def test_single_sequence():
    seqs = dict(MinimalPhylipParser(SINGLE_SEQUENCE.splitlines()))
    assert seqs == {"seq1": "ACGTACGTACGTACGTACGT"}
