---
title: "Applying a discrete-time, non-stationary nucleotide model"
---
```{python}
#| echo: false
import plotly.io as pio

pio.renderers.default = "plotly_mimetype+notebook_connected"
```

We fit a discrete-time Markov nucleotide model. This corresponds to a Barry and Hartigan 1987 model.

```{python}
from cogent3 import get_app

loader = get_app("load_aligned", format_name="fasta", moltype="dna")
aln = loader("data/primate_brca1.fasta")
model = get_app("model", "BH", tree="data/primate_brca1.tree")
result = model(aln)
result
```

::: {.callout-note}
DLC stands for diagonal largest in column and the value is a check on the identifiability of the model. `unique_Q` is another identifiability check, but it not applicable to a discrete-time model and so remains as `None`.
:::

Looking at the likelihood function, we see these maximum likelihood estimated values

```{python}
result.lf
```

## Get a tree with branch lengths as paralinear

This is the only possible length metric for a discrete-time process.

```{python}
tree = result.tree
fig = tree.get_figure()
fig.scale_bar = "top right"
fig.show(width=500, height=500)
```

## Getting parameter estimates

For a discrete-time model, aside from the root motif probabilities, everything is edge specific. But note that the `tabular_result` has different keys from the continuous-time case, as demonstrated below.

```{python}
tabulator = get_app("tabulate_stats")
stats = tabulator(result)
stats
```

```{python}
stats["edge motif motif2 params"]
```
